### ISSUE TITLE
if the value is chinese,it will be messy code

### ISSUE THREAD

**Issue by xiaodiu** [fresc81/node-winreg#36]
function getPath(callback){
var Winreg = require('winreg');
        var regKey = new Winreg({
            hive: Winreg.HKCU,
            key: '\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders' 
        });
        var myPath = regKey.values(function(err, items) {          
            for (var i in items) {
                if (items[i].name === 'Personal') { 
                    callback(items[i].value);                  
                }
            }
        });
}

check this out
if the Personal value is in chinese, the value in the callback will be messy code.
does anybody know how to resolve this?

**Comment by fresc81** [comment]
I'll have a look on this later. Thanks for your report.

**Comment by xiaodiu** [comment]
thanks for reply
i found one workaround
![image](https://cloud.githubusercontent.com/assets/11209852/17584283/39c4dd94-5fe8-11e6-9cda-949a4fff0ff9.png)

**Comment by fresc81** [comment]
Yeah, seems like _winreg_ ignores the encoding in general. I think i can fix this without depending on _iconv_.

**Comment by fresc81** [comment]
You can use following command before running node to set your terminal's codepage to UTF-8:
```Batch
chcp 65001
```
You can check the current codepage in the console property dialog.
After that chinese characters were still shown as placeholders in my console but are processed correctly otherwise (I don't have support for asian languages installed on my test machine). This way I was able to output chinese letters from the registry to an UTF-8 file. The characters appeared correctly in my text editor.
Unfortunatly I wasn't able to do that from within _winreg_, it seems like this is a matter of the console your script is running.
I would leave this issue open for now.

**Comment by xiaodiu** [comment]
however ,i  need to get the output in my project not in the console .and if my project is published,does it mean that the end users also need to do chcp 65001?are you sure this solution can resolve my problem?

**Comment by fresc81** [comment]
Yes it won't get UTF-8 output from the REG.EXE if the terminal doesn't support this encoding. But you could just add something like this to your script:

```javascript
// switch terminal codepage to UTF-8
const execSync = require('child_process').execSync;
execSync('chcp 65001');
```

**Comment by fresc81** [comment]
added some notes on encoding and codepages to the README file

**Comment by Eskibear** [comment]
```
const execSync = require('child_process').execSync;
execSync('chcp 65001');
```

Above code does work for simple js script running from a shell. But it seems not to work with my electron app.  After statement `execSync('chcp 65001')`, the code page is still unchanged (e.g. 437 in my case). I don't know if it's due to electron or webpack or anything else. Do you have any rough idea about that? Thanks.

**Comment by pnpetrov** [comment]
@Eskibear I have exactly the same issue with Electron. Did you find a workaround?

**Comment by Eskibear** [comment]
@pnpetrov I made a private lib, run `chcp 65001` before `reg.exe`, FYI [diff](https://github.com/fresc81/node-winreg/compare/master...Eskibear:utf8#diff-c76cf141522a047fee59ae738cbc8a0dc2c48ed15666d958d407d867c3a4b69fR144-R145)
